plugins:
  - react
  - react-hooks
  - jsx-a11y
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
env:
  browser: true
  es6: true
  jest: true
  node: true
ignorePatterns:
  - node_modules
  - '**/*.min.js'
parser: '@typescript-eslint/parser'
overrides:
  - files:
    - '**/__tests__/**'
    - '**/*.spec.*'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
settings:
  react:
    pragma: React
    version: detect
rules:
  no-case-declarations: off
  linebreak-style: off
  arrow-body-style: off
  arrow-parens:
    - error
    - as-needed
  camelcase: off
  class-methods-use-this: off
  max-classes-per-file: off
  comma-dangle:
    - error
    - never
  default-param-last: off
  func-names:
    - error
    - as-needed
  global-require: off
  indent:
    - error
    - 2
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-useless-constructor: off
  max-len: off
  max-params: off
  new-cap:
    - error
    - capIsNewExceptions:
        - Beacon
  no-console:
    - warn
    - allow:
      - warn
      - error
      - info
  no-continue: off
  no-empty:
    - error
    - allowEmptyCatch: true
  no-extra-semi: off
  no-floating-decimal: off
  no-mixed-operators: off
  no-multi-assign: off
  no-multiple-empty-lines:
    - error
    - max: 1
  no-nested-ternary: off
  no-param-reassign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-shadow: off
  no-undef: off
  no-underscore-dangle: off
  no-unused-expressions: off
  no-use-before-define: off
  object-curly-newline: off
  object-shorthand: off
  padded-blocks: off
  prefer-arrow-callback: off
  prefer-destructuring: off
  prefer-promise-reject-errors: off
  quote-props: off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - { anonymous: never, named: never, asyncArrow: always }
  import/extensions: off
  import/first: off
  import/named: off
  import/newline-after-import: off
  import/no-cycle: off
  import/no-duplicates: off
  import/no-dynamic-require: off
  import/no-extraneous-dependencies: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/no-self-import: off
  import/no-import-module-exports: off
  import/no-unresolved: off
  import/no-useless-path-segments: off
  import/order: off
  import/prefer-default-export: off
  jsx/no-undef: off
  jsx-quotes:
    - error
    - prefer-double
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-fragments:
    - error
    - syntax
  react/react-in-jsx-scope: off
  react/jsx-curly-spacing:
    - error
    - { when: always, attributes: false, children: true }
    - spacing:
        objectLiterals: never
  react/jsx-filename-extension:
    - error
    - extensions:
        - '.js'
        - '.tsx'
  react/jsx-max-depth:
    - error
    - max: 10
  react/jsx-no-duplicate-props: error
  react/jsx-props-no-multi-spaces: error
  react/jsx-no-target-blank: off
  react/jsx-no-useless-fragment: off
  react/jsx-tag-spacing:
    - error
    - beforeSelfClosing: always
  react/no-access-state-in-setstate: error
  react/no-children-prop: error
  react/no-deprecated: error
  react/no-direct-mutation-state: error
  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/no-redundant-should-component-update: error
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unknown-property: error
  react/no-unsafe: error
  react/no-unused-state: error
  react/prop-typeS: off
  react/self-closing-comp:
    - error
    - { component: true, html: true }
  react/sort-comp: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: off
  jsx-a11y/no-autofocus: off
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y-no-noninteractive-tabindex: off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/array-type': error
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/indent':
    - error
    - 2
    - SwitchCase: 0
  '@typescript-eslint/member-delimiter-style': error
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-inferrable-types': error
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/semi': error
  consistent-return: off
